# 3. Data adaption

## While using Tableau, some additinoal data cleanings are needed.

In [34]:
import pandas as pd
import datetime

#### Cross-check the "all_time_available" filter, as some arrival time are missing, altought the filter indicates the opposite.

In [25]:
df = pd.read_pickle("/Users/Tianwang/ironhack/git/03_project_ironhack_tableau/data/baton_rouge_animal_control_incidents_clean_update.pkl")

In [26]:
df.head()

,file_number,incident_date,complainant_street,location,municipality,zip_code,service_code,species,breed,condition,...,arrival_time_new,available_time_new,incident_time_new,dispatched_time_new,all_time_available,incident_to_dispatch,disp_to_arrival,service_code_summary,species_clean,clean_adress
0,201639027,12/27/2016,SYCAMORE ST,3366 SYCAMORE,BATON ROUGE,70805,LOOSE,DOG,PITBULL,FAIR,...,2016-12-27 16:17:00,2016-12-27 16:38:00,2016-12-27 15:30:00,2016-12-27 16:06:00,Yes,36.0,11.0,LOOSE,DOG,"3366 SYCAMORE, BATON ROUGE, 70805"
1,201639044,12/28/2016,WOODLAND RIDGE BL,2582 WOODLAND RIDGE,BATON ROUGE,70816,TRAPPED ANIMAL,WILDLIFE,POSSUM,FAIR,...,2016-12-28 10:15:00,2016-12-28 10:23:00,2016-12-28 10:06:00,2016-12-28 10:07:00,Yes,1.0,8.0,TRAPPED ANIMAL,WILDLIFE,"2582 WOODLAND RIDGE, BATON ROUGE, 70816"
2,201639036,12/28/2016,MAIN ST,4463 MAIN,ZACHARY,70791,STRAY AND SECURED,DOG,PITBULL,EMACIATED,...,2016-12-28 09:27:00,2016-12-28 09:45:00,2016-12-28 09:03:00,2016-12-28 09:03:00,Yes,0.0,24.0,STRAY,DOG,"4463 MAIN, ZACHARY, 70791"
3,201639042,12/28/2016,ERIE ST,2100 ERIE,BATON ROUGE,70805,ABANDONED ANIMAL,DOG,GERMAN SHEPHERD,EMACIATED,...,2016-12-28 10:35:00,2016-12-28 10:47:00,2016-12-28 09:46:00,2016-12-28 10:24:00,Yes,38.0,11.0,ABANDONED ANIMAL,DOG,"2100 ERIE, BATON ROUGE, 70805"
4,201639059,12/28/2016,VAN BUREN ST,299 VAN BUREN,BATON ROUGE,70714,STRAY,DOG,YORKSHIRE TERRIER,EMACIATED,...,2016-12-28 16:07:00,2016-12-28 16:25:00,2016-12-28 15:05:00,2016-12-28 15:45:00,Yes,40.0,22.0,STRAY,DOG,"299 VAN BUREN, BATON ROUGE, 70714"

In [28]:
df_time_available = df[df["all_time_available"]=="Yes"]

In [29]:
df_time_available.loc[df_time_available["incident_time_new"].isna()]

Empty DataFrame
Columns: [file_number, incident_date, complainant_street, location, municipality, zip_code, service_code, species, breed, condition, temperment, arrival_time_new, available_time_new, incident_time_new, dispatched_time_new, all_time_available, incident_to_dispatch, disp_to_arrival, service_code_summary, species_clean, clean_adress]
Index: []

[0 rows x 21 columns]

In [36]:
df = pd.read_csv("/Users/Tianwang/ironhack/git/03_project_ironhack_tableau/data/raw_data_Animal_Control_Incidents.csv")

In [39]:
df.columns

Index(['FILE NUMBER', 'INCIDENT DATE', 'INCIDENT TIME', 'DISPATCHED TIME',
       'CALL TAKER', 'DISPATCHER', 'DISPATCHED OTHER', 'DISPATCHED SITUATION',
       'ARRIVAL TIME', 'AVAILABLE TIME', 'COMPLAINANT STREET ', 'REQUEST TYPE',
       'OFFICER', 'EQUIPMENT NUMBER', 'REMARKS', 'IMPOUND NUMBER',
       'IMPOUND DATE', 'IMPOUND TIME', 'LOCATION', 'MUNICIPALITY ', 'ZIP CODE',
       'SERVICE CODE', 'SPECIES', 'BREED', 'SEX', 'SIZE', 'COLOR', 'AGE',
       'CONDITION', 'TEMPERMENT', 'COLLAR', 'COLLAR COLOR',
       'VACCINATION NUMBER', 'VACCINATION DATE', 'PET NAME', 'DISPOSITION',
       'DISPOSITION DATE', 'DISPOSITION OFFICER'],
      dtype='object')

In [46]:
test = df[df["LOCATION"]=="5821 SUMRALL"]

In [47]:
test.to_csv("test.csv")

In [50]:
test.drop_duplicates(keep=False,inplace=False)

,FILE NUMBER,INCIDENT DATE,INCIDENT TIME,DISPATCHED TIME,CALL TAKER,DISPATCHER,DISPATCHED OTHER,DISPATCHED SITUATION,ARRIVAL TIME,AVAILABLE TIME,...,CONDITION,TEMPERMENT,COLLAR,COLLAR COLOR,VACCINATION NUMBER,VACCINATION DATE,PET NAME,DISPOSITION,DISPOSITION DATE,DISPOSITION OFFICER
8345,201745478,06/14/2017,10:06,10:07,UNKNOWN,JENNIFER G,0,D,10:26,11:04,...,FAIR,NERVOUS,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,06/14/2017,LW
20263,201856466,04/02/2018,09:51,09:59,UNKNOWN,JENNIFER G,0,D,10:15,11:12,...,FAIR,NORMAL,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,NaN,ALLISON C
20266,201856466,04/02/2018,09:51,09:59,UNKNOWN,JENNIFER G,0,D,10:15,11:12,...,FAIR,NORMAL,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,NaN,ALLISON C
20272,201856466,04/02/2018,09:51,09:59,UNKNOWN,JENNIFER G,0,D,10:15,11:12,...,FAIR,NORMAL,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,NaN,ALLISON C
20289,201856466,04/02/2018,09:51,09:59,UNKNOWN,JENNIFER G,0,D,10:15,11:12,...,FAIR,NORMAL,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,NaN,ALLISON C
20295,201856466,04/02/2018,09:51,09:59,UNKNOWN,JENNIFER G,0,D,10:15,11:12,...,FAIR,NORMAL,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,NaN,ALLISON C
20303,201856466,04/02/2018,09:51,09:59,UNKNOWN,JENNIFER G,0,D,10:15,11:12,...,FAIR,NORMAL,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,NaN,ALLISON C
20308,201856466,04/02/2018,09:51,09:59,UNKNOWN,JENNIFER G,0,D,10:15,11:12,...,FAIR,NORMAL,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,NaN,ALLISON C
20310,201856466,04/02/2018,09:51,09:59,UNKNOWN,JENNIFER G,0,D,10:15,11:12,...,FAIR,NORMAL,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,NaN,ALLISON C
20315,201856466,04/02/2018,09:51,09:59,UNKNOWN,JENNIFER G,0,D,10:15,11:12,...,FAIR,NORMAL,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,NaN,ALLISON C
20326,201856466,04/02/2018,09:51,09:59,UNKNOWN,JENNIFER G,0,D,10:15,11:12,...,FAIR,NORMAL,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,NaN,ALLISON C
20329,201856466,04/02/2018,09:51,09:59,UNKNOWN,JENNIFER G,0,D,10:15,11:12,...,EMACIATED,NORMAL,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,NaN,ALLISON C
20333,201856466,04/02/2018,09:51,09:59,UNKNOWN,JENNIFER G,0,D,10:15,11:12,...,FAIR,NERVOUS,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,NaN,ALLISON C
20347,201856466,04/02/2018,09:51,09:59,UNKNOWN,JENNIFER G,0,D,10:15,11:12,...,FAIR,NORMAL,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,NaN,ALLISON C
20349,201856466,04/02/2018,09:51,09:59,UNKNOWN,JENNIFER G,0,D,10:15,11:12,...,FAIR,NORMAL,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,NaN,ALLISON C
20350,201856466,04/02/2018,09:51,09:59,UNKNOWN,JENNIFER G,0,D,10:15,11:12,...,FAIR,NORMAL,UNKNOWN,UNKNOWN,NaN,NaN,NaN,TRANS CAA,NaN,ALLISON C

In [60]:
test.iloc[:,19]

8345     BATON ROUGE
20263    BATON ROUGE
20266    BATON ROUGE
20272    BATON ROUGE
20289    BATON ROUGE
20295    BATON ROUGE
20303    BATON ROUGE
20308    BATON ROUGE
20310    BATON ROUGE
20315    BATON ROUGE
20326    BATON ROUGE
20329    BATON ROUGE
20333    BATON ROUGE
20347    BATON ROUGE
20349    BATON ROUGE
20350    BATON ROUGE
Name: MUNICIPALITY , dtype: object